#! /bin/sh

bspc monitor -d \
    web \
    term \
    code \
    music \
    5 \
    6 \
    7 \
    8 \
    9 \
    10

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a spotify desktop='^4'

numlockx &
compton &
feh --bg-scale ~/pictures/car1.jpg &
xscreensaver -no-splash &
~/.config/polybar/launch.sh
spotify &

